"""
Shared constants for TECHNOVA.
"""

# Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# String limits
MAX_BUSINESS_NAME_LENGTH = 200
MAX_DESCRIPTION_LENGTH = 2000
MAX_PHONE_LENGTH = 20
MAX_EMAIL_LENGTH = 254
MAX_ADDRESS_LENGTH = 500
MAX_LICENSE_LENGTH = 100
MAX_URL_LENGTH = 2000

# Verification
VERIFICATION_DOCUMENT_MAX_SIZE_MB = 10
VERIFICATION_ALLOWED_TYPES = ["application/pdf", "image/jpeg", "image/png", "image/webp"]

# API
API_V1_PREFIX = "/api/v1"
